stages:
  - lint
  - deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
    - $HOME/.yarn

lint:
  image: node:12
  stage: lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - yarn install
    - yarn lint

deploy-staging:
  stage: deploy
  image: node:12

  variables:
    PREVIEW_URL: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app

  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.$VERCEL_SCOPE.vercel.app

  script:
    - npm i -g vercel
    - echo $(vercel --name $CI_PROJECT_NAME --confirm -t $VERCEL_TOKEN) > .deployment
    - vercel alias set $(cat .deployment) $PREVIEW_URL -t $VERCEL_TOKEN
  after_script:
    - vercel logs $(cat .deployment) -t $VERCEL_TOKEN


deploy-production:
  stage: deploy
  image: node:12
  only:
    - master
  environment:
    name: vercel/production
    url: $VERCEL_PROD_URL
  script:
    - npm i -g vercel
    - vercel --name $CI_PROJECT_NAME --confirm --prod -t $VERCEL_TOKEN
  after_script:
    - vercel logs $VERCEL_PROD_URL -t $VERCEL_TOKEN
