image: node:12-alpine

stages:
  - package
  - build

before_script:
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
    - $HOME/.yarn

build:
  stage: build
  script:
    - yarn install
    - yarn build

include:
  - project: internal/ci
    file: dockerize.yaml

dockerize:
  stage: package
  only:
    - master
